services:
  airflow-webserver:
    build: .  # Dockerfile 위치
    container_name: tinybert_ml_airflow
    ports:
      - "8080:8080"  # Airflow Webserver accessible at localhost:8080
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////usr/local/airflow/airflow.db
      - DATA_PATH=/data/IMDB_Dataset.csv  # Dataset path
      - DATASET_PATH=/data/tk_dataset  # Processed dataset path
      - MODEL_PATH=/data/models/tinybert_model_test  # Model save path
    networks:
      - airflow_network
    volumes:
      - "./dags:/usr/local/airflow/dags"  # DAG files
      - "./models:/usr/local/airflow/models"  # Model storage
      - "./data:/data"  # Dataset and processed data storage
    depends_on:
      - mlflow
    command: >
      bash -c "airflow webserver -p 8080 & airflow scheduler"

  mlflow:
    build:
      context: .  # Directory containing the Dockerfile for MLflow
      dockerfile: Dockerfile.mlflow
    container_name: tinybert_ml_mlflow
    ports:
      - "5001:5001"  # MLflow UI accessible at localhost:5001
    environment:
      - MLFLOW_TRACKING_URI=http://127.0.0.1:5001  # Add MLflow connection
    networks:
      - airflow_network
    volumes:
      - "./mlruns:/mlruns"  # Persist MLflow artifacts

networks:
  airflow_network:
    driver: bridge